[package]
name = "keystone"
version = "0.1.0"
authors = ["Ta Thanh Dinh <tathanhdinh@gmail.com>"]
description = "High-level bindings for Keystone assembler"

[dependencies]
keystone-sys = { path = "keystone-sys" }
